image: blang/latex

build:
  before_script:
    - apt-get update
    - apt-get install -y curl
  script:
    - latexmk -pdf thesis.tex
  after_script:
    - curl -u $NUAGE_LIP6_U:$NUAGE_LIP6_P -T thesis.pdf https://nuage.lip6.fr/remote.php/dav/files/$NUAGE_LIP6_U/thesis.pdf
  artifacts:
    paths:
      - thesis.pdf
